// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: match/league.proto

package match

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Leagues 联赛
type Leagues struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"id"`
	Code                 string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"code"`
	Logo                 string   `protobuf:"bytes,3,opt,name=Logo,proto3" json:"logo"`
	Name                 string   `protobuf:"bytes,4,opt,name=Name,proto3" json:"name"`
	EnName               string   `protobuf:"bytes,5,opt,name=EnName,proto3" json:"en_name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Leagues) Reset()         { *m = Leagues{} }
func (m *Leagues) String() string { return proto.CompactTextString(m) }
func (*Leagues) ProtoMessage()    {}
func (*Leagues) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b7f8f1cabb4e48d, []int{0}
}
func (m *Leagues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Leagues.Unmarshal(m, b)
}
func (m *Leagues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Leagues.Marshal(b, m, deterministic)
}
func (m *Leagues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Leagues.Merge(m, src)
}
func (m *Leagues) XXX_Size() int {
	return xxx_messageInfo_Leagues.Size(m)
}
func (m *Leagues) XXX_DiscardUnknown() {
	xxx_messageInfo_Leagues.DiscardUnknown(m)
}

var xxx_messageInfo_Leagues proto.InternalMessageInfo

func (m *Leagues) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Leagues) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Leagues) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *Leagues) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Leagues) GetEnName() string {
	if m != nil {
		return m.EnName
	}
	return ""
}

// LeaguesClub 俱乐部
type LeaguesClub struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"id"`
	Code                 string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"code"`
	Logo                 string   `protobuf:"bytes,3,opt,name=Logo,proto3" json:"logo"`
	Name                 string   `protobuf:"bytes,4,opt,name=Name,proto3" json:"name"`
	EnName               string   `protobuf:"bytes,5,opt,name=EnName,proto3" json:"en_name"`
	Fans                 uint64   `protobuf:"varint,6,opt,name=Fans,proto3" json:"fans"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaguesClub) Reset()         { *m = LeaguesClub{} }
func (m *LeaguesClub) String() string { return proto.CompactTextString(m) }
func (*LeaguesClub) ProtoMessage()    {}
func (*LeaguesClub) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b7f8f1cabb4e48d, []int{1}
}
func (m *LeaguesClub) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaguesClub.Unmarshal(m, b)
}
func (m *LeaguesClub) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaguesClub.Marshal(b, m, deterministic)
}
func (m *LeaguesClub) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaguesClub.Merge(m, src)
}
func (m *LeaguesClub) XXX_Size() int {
	return xxx_messageInfo_LeaguesClub.Size(m)
}
func (m *LeaguesClub) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaguesClub.DiscardUnknown(m)
}

var xxx_messageInfo_LeaguesClub proto.InternalMessageInfo

func (m *LeaguesClub) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *LeaguesClub) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *LeaguesClub) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *LeaguesClub) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LeaguesClub) GetEnName() string {
	if m != nil {
		return m.EnName
	}
	return ""
}

func (m *LeaguesClub) GetFans() uint64 {
	if m != nil {
		return m.Fans
	}
	return 0
}

// LeaguesClubs 联赛下的俱乐部
type LeaguesTree struct {
	Code                 string         `protobuf:"bytes,1,opt,name=Code,proto3" json:"code"`
	Logo                 string         `protobuf:"bytes,2,opt,name=Logo,proto3" json:"logo"`
	Name                 string         `protobuf:"bytes,3,opt,name=Name,proto3" json:"name"`
	EnName               string         `protobuf:"bytes,4,opt,name=EnName,proto3" json:"en_name"`
	Clubs                []*LeaguesClub `protobuf:"bytes,5,rep,name=Clubs,proto3" json:"clubs"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *LeaguesTree) Reset()         { *m = LeaguesTree{} }
func (m *LeaguesTree) String() string { return proto.CompactTextString(m) }
func (*LeaguesTree) ProtoMessage()    {}
func (*LeaguesTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b7f8f1cabb4e48d, []int{2}
}
func (m *LeaguesTree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaguesTree.Unmarshal(m, b)
}
func (m *LeaguesTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaguesTree.Marshal(b, m, deterministic)
}
func (m *LeaguesTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaguesTree.Merge(m, src)
}
func (m *LeaguesTree) XXX_Size() int {
	return xxx_messageInfo_LeaguesTree.Size(m)
}
func (m *LeaguesTree) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaguesTree.DiscardUnknown(m)
}

var xxx_messageInfo_LeaguesTree proto.InternalMessageInfo

func (m *LeaguesTree) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *LeaguesTree) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *LeaguesTree) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LeaguesTree) GetEnName() string {
	if m != nil {
		return m.EnName
	}
	return ""
}

func (m *LeaguesTree) GetClubs() []*LeaguesClub {
	if m != nil {
		return m.Clubs
	}
	return nil
}

// LeaguesResponse 返回 联赛
type LeaguesResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"message"`
	Data                 *Leagues `protobuf:"bytes,2,opt,name=Data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaguesResponse) Reset()         { *m = LeaguesResponse{} }
func (m *LeaguesResponse) String() string { return proto.CompactTextString(m) }
func (*LeaguesResponse) ProtoMessage()    {}
func (*LeaguesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b7f8f1cabb4e48d, []int{3}
}
func (m *LeaguesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaguesResponse.Unmarshal(m, b)
}
func (m *LeaguesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaguesResponse.Marshal(b, m, deterministic)
}
func (m *LeaguesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaguesResponse.Merge(m, src)
}
func (m *LeaguesResponse) XXX_Size() int {
	return xxx_messageInfo_LeaguesResponse.Size(m)
}
func (m *LeaguesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaguesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeaguesResponse proto.InternalMessageInfo

func (m *LeaguesResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LeaguesResponse) GetData() *Leagues {
	if m != nil {
		return m.Data
	}
	return nil
}

// LeaguesesResponse 返回 联赛列表
type LeaguesesResponse struct {
	Message              string     `protobuf:"bytes,1,opt,name=Message,proto3" json:"message"`
	Data                 []*Leagues `protobuf:"bytes,2,rep,name=Data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LeaguesesResponse) Reset()         { *m = LeaguesesResponse{} }
func (m *LeaguesesResponse) String() string { return proto.CompactTextString(m) }
func (*LeaguesesResponse) ProtoMessage()    {}
func (*LeaguesesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b7f8f1cabb4e48d, []int{4}
}
func (m *LeaguesesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaguesesResponse.Unmarshal(m, b)
}
func (m *LeaguesesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaguesesResponse.Marshal(b, m, deterministic)
}
func (m *LeaguesesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaguesesResponse.Merge(m, src)
}
func (m *LeaguesesResponse) XXX_Size() int {
	return xxx_messageInfo_LeaguesesResponse.Size(m)
}
func (m *LeaguesesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaguesesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeaguesesResponse proto.InternalMessageInfo

func (m *LeaguesesResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LeaguesesResponse) GetData() []*Leagues {
	if m != nil {
		return m.Data
	}
	return nil
}

// LeaguesTreeResponse 联赛球队（树状结构）
type LeaguesTreeResponse struct {
	Message              string         `protobuf:"bytes,1,opt,name=Message,proto3" json:"message"`
	Data                 []*LeaguesTree `protobuf:"bytes,2,rep,name=Data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *LeaguesTreeResponse) Reset()         { *m = LeaguesTreeResponse{} }
func (m *LeaguesTreeResponse) String() string { return proto.CompactTextString(m) }
func (*LeaguesTreeResponse) ProtoMessage()    {}
func (*LeaguesTreeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b7f8f1cabb4e48d, []int{5}
}
func (m *LeaguesTreeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaguesTreeResponse.Unmarshal(m, b)
}
func (m *LeaguesTreeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaguesTreeResponse.Marshal(b, m, deterministic)
}
func (m *LeaguesTreeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaguesTreeResponse.Merge(m, src)
}
func (m *LeaguesTreeResponse) XXX_Size() int {
	return xxx_messageInfo_LeaguesTreeResponse.Size(m)
}
func (m *LeaguesTreeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaguesTreeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeaguesTreeResponse proto.InternalMessageInfo

func (m *LeaguesTreeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LeaguesTreeResponse) GetData() []*LeaguesTree {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Leagues)(nil), "match.Leagues")
	proto.RegisterType((*LeaguesClub)(nil), "match.LeaguesClub")
	proto.RegisterType((*LeaguesTree)(nil), "match.LeaguesTree")
	proto.RegisterType((*LeaguesResponse)(nil), "match.LeaguesResponse")
	proto.RegisterType((*LeaguesesResponse)(nil), "match.LeaguesesResponse")
	proto.RegisterType((*LeaguesTreeResponse)(nil), "match.LeaguesTreeResponse")
}

func init() { proto.RegisterFile("match/league.proto", fileDescriptor_6b7f8f1cabb4e48d) }

var fileDescriptor_6b7f8f1cabb4e48d = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x93, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0xc9, 0x6f, 0xed, 0x04, 0x2d, 0x8e, 0x20, 0x41, 0x84, 0x94, 0x88, 0xd0, 0x85, 0xa4,
	0xd2, 0x2e, 0xdd, 0xa5, 0x55, 0x28, 0x54, 0x17, 0x83, 0x2b, 0x37, 0x32, 0x6d, 0x6e, 0x53, 0xa1,
	0x99, 0x29, 0x9d, 0xf4, 0x7d, 0x7c, 0x15, 0x7d, 0x90, 0x3c, 0x40, 0x9e, 0x42, 0x72, 0x93, 0xda,
	0x1f, 0xb0, 0x2a, 0x6e, 0xdc, 0x64, 0x71, 0xbe, 0xc3, 0x3d, 0xe7, 0xde, 0x24, 0x84, 0x26, 0x3c,
	0x1d, 0x4f, 0xdb, 0x33, 0xe0, 0xf1, 0x12, 0x82, 0xf9, 0x42, 0xa6, 0x92, 0x5a, 0xa8, 0x9d, 0x39,
	0xb1, 0x6c, 0xc7, 0xb2, 0xd4, 0xfc, 0x57, 0x8d, 0xd4, 0x86, 0x68, 0x52, 0xf4, 0x94, 0xe8, 0x83,
	0xbe, 0xab, 0x35, 0xb5, 0x96, 0x19, 0xda, 0x79, 0xe6, 0xe9, 0x2f, 0x11, 0xd3, 0x07, 0x7d, 0x7a,
	0x4e, 0xcc, 0x9e, 0x8c, 0xc0, 0xd5, 0x9b, 0x5a, 0xab, 0x1e, 0x1e, 0xe4, 0x99, 0x67, 0x8e, 0x65,
	0x04, 0x0c, 0xd5, 0x82, 0x0e, 0x65, 0x2c, 0x5d, 0x63, 0x4d, 0x67, 0x32, 0x96, 0x0c, 0xd5, 0x82,
	0x3e, 0xf0, 0x04, 0x5c, 0x73, 0x4d, 0x05, 0x4f, 0x80, 0xa1, 0x4a, 0x2f, 0x88, 0x7d, 0x2b, 0x90,
	0x5b, 0xc8, 0x9d, 0x3c, 0xf3, 0x6a, 0x20, 0x9e, 0xd1, 0x52, 0x21, 0xff, 0x5d, 0x23, 0x4e, 0x55,
	0xb1, 0x37, 0x5b, 0x8e, 0xfe, 0x69, 0xcd, 0x62, 0xc4, 0x1d, 0x17, 0xca, 0xb5, 0xb1, 0x18, 0x8e,
	0x98, 0x70, 0xa1, 0x18, 0xaa, 0xfe, 0xdb, 0x7a, 0x89, 0xc7, 0x05, 0xc0, 0x67, 0x59, 0x6d, 0x6f,
	0x59, 0x7d, 0x6f, 0x59, 0xe3, 0x9b, 0xb2, 0xe6, 0xd7, 0x65, 0xbb, 0xc4, 0x2a, 0x6e, 0xa9, 0x5c,
	0xab, 0x69, 0xb4, 0x9c, 0x0e, 0x0d, 0xf0, 0xd3, 0x08, 0x36, 0xce, 0x1c, 0xd6, 0xf3, 0xcc, 0xb3,
	0xc6, 0x85, 0x89, 0x95, 0x5e, 0x7f, 0x42, 0x1a, 0x95, 0x81, 0x81, 0x9a, 0x4b, 0xa1, 0x80, 0x5e,
	0x92, 0xda, 0x3d, 0x28, 0xc5, 0xe3, 0xd5, 0x26, 0x98, 0x96, 0x94, 0x12, 0x5b, 0x31, 0x7a, 0x45,
	0xcc, 0x3e, 0x4f, 0x39, 0xee, 0xe3, 0x74, 0x8e, 0xb6, 0xd3, 0xca, 0x0d, 0x22, 0x9e, 0x72, 0x86,
	0x2e, 0x7f, 0x4a, 0x8e, 0x2b, 0xf4, 0x97, 0x24, 0xe3, 0x07, 0x49, 0x82, 0x9c, 0x6c, 0xbc, 0x94,
	0xdf, 0x66, 0x5d, 0x6f, 0x65, 0xed, 0xdc, 0xb0, 0x18, 0xb8, 0x9b, 0x17, 0x36, 0x9e, 0x0e, 0x83,
	0x36, 0xda, 0x6e, 0xf0, 0x39, 0xb2, 0xf1, 0x2f, 0xec, 0x7e, 0x04, 0x00, 0x00, 0xff, 0xff, 0x18,
	0x92, 0x2f, 0xa4, 0xaf, 0x03, 0x00, 0x00,
}
