// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: match/league.proto

package match

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LeaguesClub 俱乐部
type LeaguesClub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   string `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Logo   string `protobuf:"bytes,2,opt,name=logo,proto3" json:"logo"`
	Name   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	EnName string `protobuf:"bytes,4,opt,name=en_name,json=enName,proto3" json:"en_name"`
	Fans   uint64 `protobuf:"varint,5,opt,name=fans,proto3" json:"fans"`
}

func (x *LeaguesClub) Reset() {
	*x = LeaguesClub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_league_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaguesClub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaguesClub) ProtoMessage() {}

func (x *LeaguesClub) ProtoReflect() protoreflect.Message {
	mi := &file_match_league_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaguesClub.ProtoReflect.Descriptor instead.
func (*LeaguesClub) Descriptor() ([]byte, []int) {
	return file_match_league_proto_rawDescGZIP(), []int{0}
}

func (x *LeaguesClub) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LeaguesClub) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *LeaguesClub) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LeaguesClub) GetEnName() string {
	if x != nil {
		return x.EnName
	}
	return ""
}

func (x *LeaguesClub) GetFans() uint64 {
	if x != nil {
		return x.Fans
	}
	return 0
}

// LeaguesClubs 联赛下的俱乐部
type LeaguesTree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   string         `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Logo   string         `protobuf:"bytes,2,opt,name=logo,proto3" json:"logo"`
	Name   string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	EnName string         `protobuf:"bytes,4,opt,name=en_name,json=enName,proto3" json:"en_name"`
	Clubs  []*LeaguesClub `protobuf:"bytes,5,rep,name=clubs,proto3" json:"clubs"`
}

func (x *LeaguesTree) Reset() {
	*x = LeaguesTree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_league_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaguesTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaguesTree) ProtoMessage() {}

func (x *LeaguesTree) ProtoReflect() protoreflect.Message {
	mi := &file_match_league_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaguesTree.ProtoReflect.Descriptor instead.
func (*LeaguesTree) Descriptor() ([]byte, []int) {
	return file_match_league_proto_rawDescGZIP(), []int{1}
}

func (x *LeaguesTree) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LeaguesTree) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *LeaguesTree) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LeaguesTree) GetEnName() string {
	if x != nil {
		return x.EnName
	}
	return ""
}

func (x *LeaguesTree) GetClubs() []*LeaguesClub {
	if x != nil {
		return x.Clubs
	}
	return nil
}

// LeaguesClubsTree 联赛球队（树状结构）
type LeaguesClubsTree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string       `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	Data    *LeaguesTree `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (x *LeaguesClubsTree) Reset() {
	*x = LeaguesClubsTree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_league_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaguesClubsTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaguesClubsTree) ProtoMessage() {}

func (x *LeaguesClubsTree) ProtoReflect() protoreflect.Message {
	mi := &file_match_league_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaguesClubsTree.ProtoReflect.Descriptor instead.
func (*LeaguesClubsTree) Descriptor() ([]byte, []int) {
	return file_match_league_proto_rawDescGZIP(), []int{2}
}

func (x *LeaguesClubsTree) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LeaguesClubsTree) GetData() *LeaguesTree {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_match_league_proto protoreflect.FileDescriptor

var file_match_league_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x6c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x22, 0x76, 0x0a, 0x0b, 0x4c,
	0x65, 0x61, 0x67, 0x75, 0x65, 0x73, 0x43, 0x6c, 0x75, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f,
	0x67, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x6e, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x61, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x66,
	0x61, 0x6e, 0x73, 0x22, 0x8c, 0x01, 0x0a, 0x0b, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x73, 0x54,
	0x72, 0x65, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x65, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x65, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x63, 0x6c, 0x75, 0x62,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e,
	0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x73, 0x43, 0x6c, 0x75, 0x62, 0x52, 0x05, 0x63, 0x6c, 0x75,
	0x62, 0x73, 0x22, 0x54, 0x0a, 0x10, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x73, 0x43, 0x6c, 0x75,
	0x62, 0x73, 0x54, 0x72, 0x65, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x73, 0x54, 0x72,
	0x65, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x3b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_match_league_proto_rawDescOnce sync.Once
	file_match_league_proto_rawDescData = file_match_league_proto_rawDesc
)

func file_match_league_proto_rawDescGZIP() []byte {
	file_match_league_proto_rawDescOnce.Do(func() {
		file_match_league_proto_rawDescData = protoimpl.X.CompressGZIP(file_match_league_proto_rawDescData)
	})
	return file_match_league_proto_rawDescData
}

var file_match_league_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_match_league_proto_goTypes = []interface{}{
	(*LeaguesClub)(nil),      // 0: match.LeaguesClub
	(*LeaguesTree)(nil),      // 1: match.LeaguesTree
	(*LeaguesClubsTree)(nil), // 2: match.LeaguesClubsTree
}
var file_match_league_proto_depIdxs = []int32{
	0, // 0: match.LeaguesTree.clubs:type_name -> match.LeaguesClub
	1, // 1: match.LeaguesClubsTree.data:type_name -> match.LeaguesTree
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_match_league_proto_init() }
func file_match_league_proto_init() {
	if File_match_league_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_match_league_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaguesClub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_league_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaguesTree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_league_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaguesClubsTree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_match_league_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_match_league_proto_goTypes,
		DependencyIndexes: file_match_league_proto_depIdxs,
		MessageInfos:      file_match_league_proto_msgTypes,
	}.Build()
	File_match_league_proto = out.File
	file_match_league_proto_rawDesc = nil
	file_match_league_proto_goTypes = nil
	file_match_league_proto_depIdxs = nil
}
