// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: service/district.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CityList 选择地区，精确到城市
type CityList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProvinceList map[uint64]string `protobuf:"bytes,1,rep,name=province_list,json=provinceList,proto3" json:"province_list" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CityList     map[uint64]string `protobuf:"bytes,2,rep,name=city_list,json=cityList,proto3" json:"city_list" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CityList) Reset() {
	*x = CityList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_district_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CityList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityList) ProtoMessage() {}

func (x *CityList) ProtoReflect() protoreflect.Message {
	mi := &file_service_district_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityList.ProtoReflect.Descriptor instead.
func (*CityList) Descriptor() ([]byte, []int) {
	return file_service_district_proto_rawDescGZIP(), []int{0}
}

func (x *CityList) GetProvinceList() map[uint64]string {
	if x != nil {
		return x.ProvinceList
	}
	return nil
}

func (x *CityList) GetCityList() map[uint64]string {
	if x != nil {
		return x.CityList
	}
	return nil
}

// CityListResponse 返回选择地区列表
type CityListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string    `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	Data    *CityList `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (x *CityListResponse) Reset() {
	*x = CityListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_district_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CityListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityListResponse) ProtoMessage() {}

func (x *CityListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_district_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityListResponse.ProtoReflect.Descriptor instead.
func (*CityListResponse) Descriptor() ([]byte, []int) {
	return file_service_district_proto_rawDescGZIP(), []int{1}
}

func (x *CityListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CityListResponse) GetData() *CityList {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_service_district_proto protoreflect.FileDescriptor

var file_service_district_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x22, 0x90, 0x02, 0x0a, 0x08, 0x43, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x48,
	0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x43, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x09, 0x63, 0x69, 0x74, 0x79,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x43,
	0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x63, 0x69,
	0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x3f, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e,
	0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x3b, 0x0a, 0x0d, 0x43, 0x69, 0x74, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x53, 0x0a, 0x10, 0x43, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_district_proto_rawDescOnce sync.Once
	file_service_district_proto_rawDescData = file_service_district_proto_rawDesc
)

func file_service_district_proto_rawDescGZIP() []byte {
	file_service_district_proto_rawDescOnce.Do(func() {
		file_service_district_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_district_proto_rawDescData)
	})
	return file_service_district_proto_rawDescData
}

var file_service_district_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_district_proto_goTypes = []interface{}{
	(*CityList)(nil),         // 0: service.CityList
	(*CityListResponse)(nil), // 1: service.CityListResponse
	nil,                      // 2: service.CityList.ProvinceListEntry
	nil,                      // 3: service.CityList.CityListEntry
}
var file_service_district_proto_depIdxs = []int32{
	2, // 0: service.CityList.province_list:type_name -> service.CityList.ProvinceListEntry
	3, // 1: service.CityList.city_list:type_name -> service.CityList.CityListEntry
	0, // 2: service.CityListResponse.data:type_name -> service.CityList
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_service_district_proto_init() }
func file_service_district_proto_init() {
	if File_service_district_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_district_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CityList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_district_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CityListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_district_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_district_proto_goTypes,
		DependencyIndexes: file_service_district_proto_depIdxs,
		MessageInfos:      file_service_district_proto_msgTypes,
	}.Build()
	File_service_district_proto = out.File
	file_service_district_proto_rawDesc = nil
	file_service_district_proto_goTypes = nil
	file_service_district_proto_depIdxs = nil
}
