// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: we_chat/we_chat_user.proto

package we_chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeChatUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Avatar   string `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *WeChatUser) Reset() {
	*x = WeChatUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_we_chat_we_chat_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeChatUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeChatUser) ProtoMessage() {}

func (x *WeChatUser) ProtoReflect() protoreflect.Message {
	mi := &file_we_chat_we_chat_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeChatUser.ProtoReflect.Descriptor instead.
func (*WeChatUser) Descriptor() ([]byte, []int) {
	return file_we_chat_we_chat_user_proto_rawDescGZIP(), []int{0}
}

func (x *WeChatUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *WeChatUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type LoginPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *LoginPost) Reset() {
	*x = LoginPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_we_chat_we_chat_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginPost) ProtoMessage() {}

func (x *LoginPost) ProtoReflect() protoreflect.Message {
	mi := &file_we_chat_we_chat_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginPost.ProtoReflect.Descriptor instead.
func (*LoginPost) Descriptor() ([]byte, []int) {
	return file_we_chat_we_chat_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginPost) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// LoginResponse 登录返回
type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data    string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_we_chat_we_chat_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_we_chat_we_chat_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_we_chat_we_chat_user_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// WeChatUserResponse 返回 微信用户昵称 头像
type WeChatUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string      `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data    *WeChatUser `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *WeChatUserResponse) Reset() {
	*x = WeChatUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_we_chat_we_chat_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeChatUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeChatUserResponse) ProtoMessage() {}

func (x *WeChatUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_we_chat_we_chat_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeChatUserResponse.ProtoReflect.Descriptor instead.
func (*WeChatUserResponse) Descriptor() ([]byte, []int) {
	return file_we_chat_we_chat_user_proto_rawDescGZIP(), []int{3}
}

func (x *WeChatUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WeChatUserResponse) GetData() *WeChatUser {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_we_chat_we_chat_user_proto protoreflect.FileDescriptor

var file_we_chat_we_chat_user_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x77, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x77, 0x65, 0x5f, 0x63, 0x68, 0x61,
	0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x77, 0x65,
	0x5f, 0x63, 0x68, 0x61, 0x74, 0x22, 0x40, 0x0a, 0x0a, 0x57, 0x65, 0x43, 0x68, 0x61, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1f, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x50, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x3d, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x57, 0x0a, 0x12, 0x57, 0x65, 0x43, 0x68, 0x61,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x77, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2e,
	0x57, 0x65, 0x43, 0x68, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x77, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x3b, 0x77, 0x65,
	0x5f, 0x63, 0x68, 0x61, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_we_chat_we_chat_user_proto_rawDescOnce sync.Once
	file_we_chat_we_chat_user_proto_rawDescData = file_we_chat_we_chat_user_proto_rawDesc
)

func file_we_chat_we_chat_user_proto_rawDescGZIP() []byte {
	file_we_chat_we_chat_user_proto_rawDescOnce.Do(func() {
		file_we_chat_we_chat_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_we_chat_we_chat_user_proto_rawDescData)
	})
	return file_we_chat_we_chat_user_proto_rawDescData
}

var file_we_chat_we_chat_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_we_chat_we_chat_user_proto_goTypes = []interface{}{
	(*WeChatUser)(nil),         // 0: we_chat.WeChatUser
	(*LoginPost)(nil),          // 1: we_chat.LoginPost
	(*LoginResponse)(nil),      // 2: we_chat.LoginResponse
	(*WeChatUserResponse)(nil), // 3: we_chat.WeChatUserResponse
}
var file_we_chat_we_chat_user_proto_depIdxs = []int32{
	0, // 0: we_chat.WeChatUserResponse.data:type_name -> we_chat.WeChatUser
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_we_chat_we_chat_user_proto_init() }
func file_we_chat_we_chat_user_proto_init() {
	if File_we_chat_we_chat_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_we_chat_we_chat_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeChatUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_we_chat_we_chat_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_we_chat_we_chat_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_we_chat_we_chat_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeChatUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_we_chat_we_chat_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_we_chat_we_chat_user_proto_goTypes,
		DependencyIndexes: file_we_chat_we_chat_user_proto_depIdxs,
		MessageInfos:      file_we_chat_we_chat_user_proto_msgTypes,
	}.Build()
	File_we_chat_we_chat_user_proto = out.File
	file_we_chat_we_chat_user_proto_rawDesc = nil
	file_we_chat_we_chat_user_proto_goTypes = nil
	file_we_chat_we_chat_user_proto_depIdxs = nil
}
