// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: we_chat/we_chat_user.proto

package we_chat

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type WeChatUser struct {
	Avatar               string   `protobuf:"bytes,1,opt,name=Avatar,proto3" json:"avatar"`
	Nickname             string   `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"nickname"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeChatUser) Reset()         { *m = WeChatUser{} }
func (m *WeChatUser) String() string { return proto.CompactTextString(m) }
func (*WeChatUser) ProtoMessage()    {}
func (*WeChatUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_833c67c0ac086f9f, []int{0}
}
func (m *WeChatUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeChatUser.Unmarshal(m, b)
}
func (m *WeChatUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeChatUser.Marshal(b, m, deterministic)
}
func (m *WeChatUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeChatUser.Merge(m, src)
}
func (m *WeChatUser) XXX_Size() int {
	return xxx_messageInfo_WeChatUser.Size(m)
}
func (m *WeChatUser) XXX_DiscardUnknown() {
	xxx_messageInfo_WeChatUser.DiscardUnknown(m)
}

var xxx_messageInfo_WeChatUser proto.InternalMessageInfo

func (m *WeChatUser) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *WeChatUser) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type LoginPost struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"code"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginPost) Reset()         { *m = LoginPost{} }
func (m *LoginPost) String() string { return proto.CompactTextString(m) }
func (*LoginPost) ProtoMessage()    {}
func (*LoginPost) Descriptor() ([]byte, []int) {
	return fileDescriptor_833c67c0ac086f9f, []int{1}
}
func (m *LoginPost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginPost.Unmarshal(m, b)
}
func (m *LoginPost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginPost.Marshal(b, m, deterministic)
}
func (m *LoginPost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginPost.Merge(m, src)
}
func (m *LoginPost) XXX_Size() int {
	return xxx_messageInfo_LoginPost.Size(m)
}
func (m *LoginPost) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginPost.DiscardUnknown(m)
}

var xxx_messageInfo_LoginPost proto.InternalMessageInfo

func (m *LoginPost) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

// LoginResponse 登录返回
type LoginResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"message"`
	Data                 string   `protobuf:"bytes,2,opt,name=Data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_833c67c0ac086f9f, []int{2}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LoginResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// WeChatUserResponse 返回 微信用户昵称 头像
type WeChatUserResponse struct {
	Message              string      `protobuf:"bytes,1,opt,name=Message,proto3" json:"message"`
	Data                 *WeChatUser `protobuf:"bytes,2,opt,name=Data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *WeChatUserResponse) Reset()         { *m = WeChatUserResponse{} }
func (m *WeChatUserResponse) String() string { return proto.CompactTextString(m) }
func (*WeChatUserResponse) ProtoMessage()    {}
func (*WeChatUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_833c67c0ac086f9f, []int{3}
}
func (m *WeChatUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeChatUserResponse.Unmarshal(m, b)
}
func (m *WeChatUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeChatUserResponse.Marshal(b, m, deterministic)
}
func (m *WeChatUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeChatUserResponse.Merge(m, src)
}
func (m *WeChatUserResponse) XXX_Size() int {
	return xxx_messageInfo_WeChatUserResponse.Size(m)
}
func (m *WeChatUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WeChatUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WeChatUserResponse proto.InternalMessageInfo

func (m *WeChatUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *WeChatUserResponse) GetData() *WeChatUser {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*WeChatUser)(nil), "we_chat.WeChatUser")
	proto.RegisterType((*LoginPost)(nil), "we_chat.LoginPost")
	proto.RegisterType((*LoginResponse)(nil), "we_chat.LoginResponse")
	proto.RegisterType((*WeChatUserResponse)(nil), "we_chat.WeChatUserResponse")
}

func init() { proto.RegisterFile("we_chat/we_chat_user.proto", fileDescriptor_833c67c0ac086f9f) }

var fileDescriptor_833c67c0ac086f9f = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xa9, 0x94, 0x24, 0x9d, 0xe8, 0xc1, 0xed, 0xa5, 0x14, 0x21, 0xb2, 0x20, 0xd4, 0x4b,
	0x8a, 0x7a, 0xf4, 0x64, 0xeb, 0x51, 0x45, 0x16, 0x45, 0xe8, 0xa5, 0x8c, 0xc9, 0x90, 0x16, 0xe9,
	0x4e, 0xc9, 0xae, 0xfa, 0xb6, 0x79, 0x80, 0x3c, 0x85, 0xb8, 0x9d, 0x58, 0xf1, 0xe6, 0x69, 0xe0,
	0xfb, 0x67, 0xbf, 0xdd, 0xfd, 0x61, 0xfc, 0x49, 0xcb, 0x62, 0x85, 0x7e, 0x2a, 0x73, 0xf9, 0xee,
	0xa8, 0xce, 0xb7, 0x35, 0x7b, 0x56, 0xb1, 0xb0, 0x71, 0x5a, 0xf1, 0xb4, 0xe2, 0x1d, 0xd5, 0x0b,
	0x80, 0x17, 0x9a, 0xaf, 0xd0, 0x3f, 0x3b, 0xaa, 0x95, 0x86, 0xe8, 0xe6, 0x03, 0x3d, 0xd6, 0xa3,
	0xde, 0x69, 0x6f, 0x32, 0x98, 0x41, 0xdb, 0x64, 0x11, 0x06, 0x62, 0x24, 0x51, 0x13, 0x48, 0x1e,
	0xd6, 0xc5, 0x9b, 0xc5, 0x0d, 0x8d, 0x0e, 0xc2, 0xd6, 0x61, 0xdb, 0x64, 0x89, 0x15, 0x66, 0x7e,
	0x52, 0x7d, 0x0e, 0x83, 0x3b, 0xae, 0xd6, 0xf6, 0x91, 0x9d, 0x57, 0x27, 0xd0, 0x9f, 0x73, 0x49,
	0x22, 0x4e, 0xda, 0x26, 0xeb, 0x17, 0x5c, 0x92, 0x09, 0x54, 0x3f, 0xc1, 0x51, 0x58, 0x35, 0xe4,
	0xb6, 0x6c, 0x1d, 0xa9, 0x33, 0x88, 0xef, 0xc9, 0x39, 0xac, 0xba, 0x13, 0x69, 0xdb, 0x64, 0xf1,
	0x66, 0x87, 0x4c, 0x97, 0x7d, 0x5b, 0x6f, 0xd1, 0xa3, 0x3c, 0x24, 0x58, 0x4b, 0xf4, 0x68, 0x02,
	0xd5, 0x16, 0xd4, 0xfe, 0x73, 0xff, 0x55, 0x5f, 0xfc, 0x52, 0xa7, 0x97, 0xc3, 0x5c, 0xea, 0xcb,
	0xf7, 0xc6, 0xbf, 0xf7, 0xcd, 0x86, 0x8b, 0xe3, 0xbc, 0xab, 0xfe, 0x5a, 0xe6, 0x6b, 0x14, 0x8a,
	0xbe, 0xfa, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x37, 0x58, 0x40, 0x9c, 0x01, 0x00, 0x00,
}
