// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: service/oss.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Oss struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key       string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Secret    string `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	Status    uint64 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Remark    string `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	CreatedAt string `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Oss) Reset() {
	*x = Oss{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_oss_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oss) ProtoMessage() {}

func (x *Oss) ProtoReflect() protoreflect.Message {
	mi := &file_service_oss_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oss.ProtoReflect.Descriptor instead.
func (*Oss) Descriptor() ([]byte, []int) {
	return file_service_oss_proto_rawDescGZIP(), []int{0}
}

func (x *Oss) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Oss) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Oss) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Oss) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Oss) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *Oss) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Oss) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateOssPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Secret string `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *CreateOssPost) Reset() {
	*x = CreateOssPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_oss_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOssPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOssPost) ProtoMessage() {}

func (x *CreateOssPost) ProtoReflect() protoreflect.Message {
	mi := &file_service_oss_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOssPost.ProtoReflect.Descriptor instead.
func (*CreateOssPost) Descriptor() ([]byte, []int) {
	return file_service_oss_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOssPost) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateOssPost) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type UpdateOssPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key    string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Secret string `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *UpdateOssPost) Reset() {
	*x = UpdateOssPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_oss_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOssPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOssPost) ProtoMessage() {}

func (x *UpdateOssPost) ProtoReflect() protoreflect.Message {
	mi := &file_service_oss_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOssPost.ProtoReflect.Descriptor instead.
func (*UpdateOssPost) Descriptor() ([]byte, []int) {
	return file_service_oss_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateOssPost) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateOssPost) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateOssPost) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type OssResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data    *Oss   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *OssResponse) Reset() {
	*x = OssResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_oss_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OssResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OssResponse) ProtoMessage() {}

func (x *OssResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_oss_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OssResponse.ProtoReflect.Descriptor instead.
func (*OssResponse) Descriptor() ([]byte, []int) {
	return file_service_oss_proto_rawDescGZIP(), []int{3}
}

func (x *OssResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OssResponse) GetData() *Oss {
	if x != nil {
		return x.Data
	}
	return nil
}

type OssListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data    []*Oss `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *OssListResponse) Reset() {
	*x = OssListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_oss_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OssListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OssListResponse) ProtoMessage() {}

func (x *OssListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_oss_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OssListResponse.ProtoReflect.Descriptor instead.
func (*OssListResponse) Descriptor() ([]byte, []int) {
	return file_service_oss_proto_rawDescGZIP(), []int{4}
}

func (x *OssListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OssListResponse) GetData() []*Oss {
	if x != nil {
		return x.Data
	}
	return nil
}

type OssPaginationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string                      `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data    *OssPaginationResponse_List `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *OssPaginationResponse) Reset() {
	*x = OssPaginationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_oss_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OssPaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OssPaginationResponse) ProtoMessage() {}

func (x *OssPaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_oss_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OssPaginationResponse.ProtoReflect.Descriptor instead.
func (*OssPaginationResponse) Descriptor() ([]byte, []int) {
	return file_service_oss_proto_rawDescGZIP(), []int{5}
}

func (x *OssPaginationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OssPaginationResponse) GetData() *OssPaginationResponse_List {
	if x != nil {
		return x.Data
	}
	return nil
}

type OssPaginationResponse_List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*Oss `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total int64  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *OssPaginationResponse_List) Reset() {
	*x = OssPaginationResponse_List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_oss_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OssPaginationResponse_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OssPaginationResponse_List) ProtoMessage() {}

func (x *OssPaginationResponse_List) ProtoReflect() protoreflect.Message {
	mi := &file_service_oss_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OssPaginationResponse_List.ProtoReflect.Descriptor instead.
func (*OssPaginationResponse_List) Descriptor() ([]byte, []int) {
	return file_service_oss_proto_rawDescGZIP(), []int{5, 0}
}

func (x *OssPaginationResponse_List) GetList() []*Oss {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *OssPaginationResponse_List) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_service_oss_proto protoreflect.FileDescriptor

var file_service_oss_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6f, 0x73, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0xad, 0x01, 0x0a,
	0x03, 0x4f, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x39, 0x0a, 0x0d,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x73, 0x73, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22, 0x49, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4f, 0x73, 0x73, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x22, 0x49, 0x0a, 0x0b, 0x4f, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x4f, 0x73, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4d, 0x0a,
	0x0f, 0x4f, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x4f, 0x73, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xaa, 0x01, 0x0a,
	0x15, 0x4f, 0x73, 0x73, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x37, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4f, 0x73, 0x73, 0x50, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x3e, 0x0a, 0x04, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x20, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4f, 0x73, 0x73, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70,
	0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_oss_proto_rawDescOnce sync.Once
	file_service_oss_proto_rawDescData = file_service_oss_proto_rawDesc
)

func file_service_oss_proto_rawDescGZIP() []byte {
	file_service_oss_proto_rawDescOnce.Do(func() {
		file_service_oss_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_oss_proto_rawDescData)
	})
	return file_service_oss_proto_rawDescData
}

var file_service_oss_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_service_oss_proto_goTypes = []interface{}{
	(*Oss)(nil),                        // 0: service.Oss
	(*CreateOssPost)(nil),              // 1: service.CreateOssPost
	(*UpdateOssPost)(nil),              // 2: service.UpdateOssPost
	(*OssResponse)(nil),                // 3: service.OssResponse
	(*OssListResponse)(nil),            // 4: service.OssListResponse
	(*OssPaginationResponse)(nil),      // 5: service.OssPaginationResponse
	(*OssPaginationResponse_List)(nil), // 6: service.OssPaginationResponse.List
}
var file_service_oss_proto_depIdxs = []int32{
	0, // 0: service.OssResponse.data:type_name -> service.Oss
	0, // 1: service.OssListResponse.data:type_name -> service.Oss
	6, // 2: service.OssPaginationResponse.data:type_name -> service.OssPaginationResponse.List
	0, // 3: service.OssPaginationResponse.List.list:type_name -> service.Oss
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_service_oss_proto_init() }
func file_service_oss_proto_init() {
	if File_service_oss_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_oss_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oss); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_oss_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOssPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_oss_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOssPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_oss_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OssResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_oss_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OssListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_oss_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OssPaginationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_oss_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OssPaginationResponse_List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_oss_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_oss_proto_goTypes,
		DependencyIndexes: file_service_oss_proto_depIdxs,
		MessageInfos:      file_service_oss_proto_msgTypes,
	}.Build()
	File_service_oss_proto = out.File
	file_service_oss_proto_rawDesc = nil
	file_service_oss_proto_goTypes = nil
	file_service_oss_proto_depIdxs = nil
}
